const {spawn}=require('node:child_process');
const fs=require('node:fs/promises');
const os=require('node:os');
const path=require('node:path');
const assert=require('node:assert/strict');
(async()=>{
 const {chromium}=require(process.argv[2]||'playwright');
 const data=await fs.mkdtemp(path.join(os.tmpdir(),'fiscal-visual-'));
 const child=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'4186',DATA_DIR:data}});
 let browser;
 try{
 for(let n=0;n<50;n++){try{if((await fetch('http://localhost:4186/api/setup')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:4186');await page.locator('[name=name]').fill('Administrador Teste');await page.locator('[name=email]').fill('teste@example.test');await page.locator('[name=password]').fill('Teste-visual-123');await page.getByRole('button',{name:'Criar espaço de trabalho'}).click();await page.getByRole('heading',{name:'Tudo sob controle, em um só lugar.'}).waitFor();
 await fs.mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/desktop.png',fullPage:true});
 await page.locator('[data-page=team]').click();await page.locator('[data-action=invite]').click();await page.locator('#invite [name=name]').fill('Apoio Fiscal');await page.locator('#invite [name=email]').fill('apoio@example.test');await page.locator('#invite [name=password]').fill('Apoio-visual-123');await page.locator('#invite button').click();await page.getByRole('heading',{name:'Apoio Fiscal',exact:true}).waitFor();
 await page.locator('[data-page=routine]').click();await page.locator('[data-open]').first().click();await page.locator('#add-activity input').fill('Atividade adicionada pelo teste');await page.locator('#add-activity button').click();await page.getByText('Atividade adicionada pelo teste',{exact:true}).waitFor();await page.locator('[data-toggle]').first().check();
 await page.locator('[data-tab=comments]').click();await page.locator('#add-note textarea').fill('Comentário de verificação');await page.locator('#add-note .print-input').setInputFiles('test-results/desktop.png');await page.locator('.print-previews img').waitFor();assert.equal(await page.locator('.print-previews img').count(),1);await page.locator('[data-remove-print]').click();assert.equal(await page.locator('.print-previews img').count(),0);await page.locator('#add-note .print-input').setInputFiles('test-results/desktop.png');await page.locator('.print-previews img').waitFor();await page.locator('#add-note button[type=submit]').click();await page.getByText('Comentário de verificação',{exact:true}).waitFor();
 await page.locator('[data-tab=executions]').click();await page.locator('#add-note textarea').fill('Execução verificada no navegador');await page.locator('#add-note textarea').evaluate(el=>{const raw=atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=');const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));const transfer=new DataTransfer();transfer.items.add(new File([bytes],'print-colado.png',{type:'image/png'}));el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:transfer,bubbles:true,cancelable:true}));});await page.locator('.print-previews img').waitFor();await page.locator('#add-note button[type=submit]').click();await page.getByText('Execução verificada no navegador',{exact:true}).waitFor();await page.locator('.saved-prints img').waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('.saved-prints img')].every(i=>i.complete&&i.naturalWidth>0));await page.screenshot({path:'test-results/detail.png',fullPage:true});
 await page.locator('[data-close]').click();await page.locator('[data-page=project]').click();assert.equal(await page.locator('.card').count(),2);await page.locator('[data-new=project]').click();await page.locator('[name=title]').fill('Projeto criado no navegador');await page.locator('#create .primary').click();await page.getByRole('heading',{name:'Projeto criado no navegador',exact:true}).waitFor();await page.locator('[data-close]').click();
 await page.locator('.card').filter({hasText:'Projeto criado no navegador'}).locator('[data-delegate-open]').click();await page.locator('#delegate-action [name=title]').fill('Validar documentos do projeto');await page.locator('#delegate-action [name=assignee]').selectOption({label:'Apoio Fiscal'});await page.locator('#delegate-action button').click();await page.locator('.delegated-action').waitFor();await page.screenshot({path:'test-results/delegation.png',fullPage:true});await page.locator('[data-close]').click();await page.getByText('Participantes temporários: Apoio Fiscal',{exact:true}).waitFor();
 const memberContext=await browser.newContext({viewport:{width:390,height:844}});const member=await memberContext.newPage();member.on('pageerror',e=>errors.push(e.message));await member.goto('http://localhost:4186');await member.locator('[name=email]').fill('apoio@example.test');await member.locator('[name=password]').fill('Apoio-visual-123');await member.getByRole('button',{name:'Entrar no painel'}).click();await member.locator('[data-page=project]').click();await member.locator('#mine-filter').check();assert.equal(await member.locator('.card').count(),1);await member.locator('[data-delegate-open]').click();assert.equal(await member.locator('#delegate-action').count(),0);await member.locator('[data-complete] textarea').fill('Documentos conferidos e validados');await member.locator('[data-complete] .print-input').setInputFiles('test-results/desktop.png');await member.locator('.print-previews img').waitFor();await member.locator('[data-complete] button[type=submit]').click();await member.getByText(/Vínculo encerrado/).waitFor();await member.locator('.saved-prints img').waitFor();await member.waitForFunction(()=>[...document.querySelectorAll('.saved-prints img')].every(i=>i.complete&&i.naturalWidth>0));await member.screenshot({path:'test-results/delegation-mobile.png',fullPage:true});await member.locator('[data-close]').click();assert.equal(await member.locator('.card').count(),0);await memberContext.close();
 await page.reload();await page.locator('[data-page=project]').click();await page.locator('.card').filter({hasText:'Projeto criado no navegador'}).locator('[data-delegate-open]').click();await page.locator('.saved-prints img').waitFor();assert.ok(await page.locator('.saved-prints img').evaluate(i=>i.complete&&i.naturalWidth>0));await page.locator('[data-close]').click();assert.equal(await page.getByText('Participantes temporários: Apoio Fiscal',{exact:true}).count(),0);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Página não deve ter rolagem horizontal');assert.deepEqual(errors,[]);console.log('QA visual: ações delegadas, participação temporária, conclusão pelo usuário e telas móveis aprovadas.');
 }finally{await browser?.close();child.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
